.gitignore
lib/govuk_personalisation.rb
lib/govuk_personalisation/account_concern.rb
spec/account_concern_spec.rb
spec/spec_helper.rb
spec/test_app/README.md
spec/test_app/app/assets/config/manifest.js
spec/test_app/app/controllers/application_controller.rb
spec/test_app/app/controllers/sessions_controller.rb
spec/test_app/config.ru
spec/test_app/config/application.rb
spec/test_app/config/boot.rb
spec/test_app/config/environment.rb
spec/test_app/config/routes.rb

`GovukPersonalisation::AccountConcern` now holds accounts-related
functionality extracted from `frontend` and `finder-frontend` that these
two apps have in common.
Trello card: https://trello.com/c/40YbnkRp/783-add-a-rails-concern-to-govukpersonalisation

Add a Rails concern to hold shared code

---

CHANGELOG.md
lib/govuk_personalisation/account_concern.rb
spec/account_concern_spec.rb

Right now we leave it up to individual apps to decide whether they
want to set
Vary: GOVUK-Account-Session
or
Cache-Control: no-store
This change means that apps won't need to worry about the `Vary`
header any more.
Setting just the `Vary` header is good when we want the user's browser
to be able to cache the page.  For example, the Transition Checker
results page can be cached, as the querystring contains all the data:
the only dynamic content on the page is the "these results are
different to the ones in your account" box, and it's no big deal if
that's missing due to the user seeing a cached copy.
Setting the `Cache-Control` header is good when we don't want to cache
the page at all, for example the `/sign-in` and `/sign-out` routes,
which manipulate the user's session.
But there's no …

Always set `Vary: GOVUK-Account-Session` response header

---

CHANGELOG.md
lib/govuk_personalisation.rb
lib/govuk_personalisation/test_helpers/features.rb
lib/govuk_personalisation/test_helpers/requests.rb
lib/govuk_personalisation/version.rb

These modules can be included in other apps' test files. Those apps can
then just call `mock_logged_in_session` instead of setting the header
manually or define this helper method multiple times in different apps.
Trello card: https://trello.com/c/HpMFjE5Q/784-add-test-helpers-to-govukpersonalisation

Add ability to set GOVUK-Account-Session

---

CHANGELOG.md
lib/govuk_personalisation/account_concern.rb
lib/govuk_personalisation/version.rb

This changes:
- `ACCOUNT_SESSION_REQUEST_HEADER_NAME` to
`ACCOUNT_SESSION_INTERNAL_HEADER_NAME`
- `ACCOUNT_SESSION_RESPONSE_HEADER_NAME` to
`ACCOUNT_SESSION_HEADER_NAME`
- `ACCOUNT_END_SESSION_RESPONSE_HEADER_NAME` to
`ACCOUNT_END_SESSION_HEADER_NAME`
`"GOVUK-Account-Session"` is the externally available header's name both
for requests and responses. It only in gets changed by Rails in the
controller, where it becomes `"HTTP_GOVUK_ACCOUNT_SESSION"`.
So it makes sense to have `"GOVUK-Account-Session"` in a constant called
`ACCOUNT_SESSION_HEADER_NAME` and have `"HTTP_GOVUK_ACCOUNT_SESSION"` in
a constant called `ACCOUNT_SESSION_INTERNAL_HEADER_NAME`.
Similarly, this also removes the `RESPONSE` qualifier from the constant
that holds `"GOVUK-Account-End-Session"` so that it now becomes …

Rename header name constants

---

CHANGELOG.md
lib/govuk_personalisation.rb
lib/govuk_personalisation/account_concern.rb
lib/govuk_personalisation/flash.rb
lib/govuk_personalisation/test_helpers/features.rb
lib/govuk_personalisation/test_helpers/requests.rb
spec/account_concern_spec.rb
spec/flash_spec.rb
spec/test_app/app/controllers/sessions_controller.rb

The flash is a special piece of per-request state in the Rails
session, useful for showing success or failure messages, or other
confirmation-style notices.  Since flash messages are in the Rails
session, they cannot be used across microservices (without sharing the
session encryption key). But that is a feature we would like.
To allow sending flash messages for account purposes between
apps (e.g., a user signs up to email notifications for a page, then
gets redirected back to that page and it has a success banner), we
have decided to add them to the account session.
This commit adds a module for managing flash messages in the session,
and adds some helper methods to the `AccountConcern` to make it easy
to use.
See https://github.com/alphagov/account-api/blob/main/docs/api.md
---
[Trello …

Add a module and methods for managing flash messages

---

CHANGELOG.md
lib/govuk_personalisation/urls.rb

Depends on https://github.com/alphagov/account-api/pull/218 & https://github.com/alphagov/frontend/pull/2951
---
We have changed the route in account-api / frontend.
---
[Trello card](https://trello.com/c/P8JbW0T8/1048-move-oauth-sign-in-start-page-from-sign-in-to-sign-in-redirect)

Change sign in path to `/sign-in/redirect`

---

CHANGELOG.md
lib/govuk_personalisation/controller_concern.rb
spec/controller_concern/sessions_spec.rb

We already do this in our Fastly configuration, but that isn't a full
solution, as our own Varnish may cache such a response.
This hasn't been an issue so far, as all session-changing pages have
been explicitly uncacheable (or had `Vary: GOVUK-Account-Session`);
but it is a problem for pages with flash messages, as the controller
concern will strip the flash from the cookie, and so if that response
gets cached, we'll switch subsequent users who visit the same
page (perhaps with the same flash message, if `Vary:
GOVUK-Account-Session-Flash` is set) to that first user's account.

Make session-change events uncacheable

---

lib/govuk_personalisation/urls.rb

We're retiring /sign-in/redirect in favour of this.
---
[Trello card](https://trello.com/c/1tMOYsbk/1218-change-sign-in-link-to-use-di-domain)

Change the sign in URL to /account

---

CHANGELOG.md
govuk_personalisation.gemspec
lib/govuk_personalisation/controller_concern.rb
spec/test_app/config/application.rb

Since we're now claiming to support two major versions of rails, we should test against both.  Fortunately, our govuk-jenkinslib gives us this by accident: we test gems against both ruby 2.6 and 2.7, and rails 7 does not support ruby 2.6.
However, since ruby 2.6 is end-of-life next month, we may want to remove it from govuk-jenkinslib and drop rails 6 compatibility in this gem after we've upgraded all the apps which use it to rails 7.
---
[Trello card](https://trello.com/c/TR4wziBW/1240-update-apps-to-rails-7)

Add support for Rails 7

---

CHANGELOG.md
lib/govuk_personalisation/urls.rb

We are in the process of moving the account home page from
`www.gov.uk/account/home` (served by Frontend) to an app on the DI side,
which is part of separating out central account features from the
`www.gov.uk` relying party.
To do so, we'll update `govuk_personalisation` with the new link and
change the controller in Frontend that currently serves that page to
redirect on to the new one. This allows us to do an environment aware
redirect.
Apps currently have the `YOUR_ACCOUNT` environment variables set (see
https://github.com/alphagov/govuk-puppet/pull/11728), which override
the URI generated by this library. This means this change is safe to be
released and it won't affect where apps send users yet.
Once we're ready, we'll make another change in Puppet and set the
environment variables …

Set default account home page to Digital Identity

---

CHANGELOG.md
lib/govuk_personalisation/urls.rb

When we move the account home page out of Frontend, some journeys will
need to redirect users to the manage emails page as the default GOV.UK
page, rather than the home page.
In order to do this, Frontend needs to know how what URL to send people
to.
Don't merge before #36

Add link to 'manage emails' page

---

.github/workflows/ci.yml
.rubocop.yml
Jenkinsfile
govuk_personalisation.gemspec
spec/controller_concern/sessions_spec.rb
spec/govuk_personalisation/flash_spec.rb
spec/govuk_personalisation/redirect_spec.rb
spec/govuk_personalisation/urls_spec.rb

As per [RFC-123](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-123-github-actions-ci.md) we're moving away from Jenkins for testing and publishing our gems via github actions.
https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions

Add github actions config and remove jenkins config

---

CHANGELOG.md
lib/govuk_personalisation/urls.rb

GOV.UK One Login (Formerly Digital Identity) have decided to move the URL of their account management dashboard. It has moved from off their programme subdomain of account.gov.uk, to an application specifical `home.account.gov.uk` domain.
Redirects are in place between the two domains, so there is no interruption to traffic, however we should point users to a canonical domain when possible.
This update makes that happen

Update URL to canonical `home.account.gov.uk` URL

---

lib/govuk_personalisation/urls.rb
spec/govuk_personalisation/urls_spec.rb

- If DIGITAL_IDENTITY_ENVIRONMENT is missing, use GOVUK_ENVIRONMENT
- Unless it's set to "production", in which case ignore.
(We aren't currently setting DIGITAL_IDENTITY_ENVIRONMENT to anything, and the DI environments integration and staging match ours, so we should use GOVUK_ENVIRONMENT as a fallback to avoid setting DIGITAL_IDENTITY_ENVIRONMENT unless we have a specific need).
https://trello.com/c/SiAQ3dZU/2086-redirect-govuk-account-to-homeaccountgovuk

Use GOVUK_ENVIRONMENT as a backstop for DIGITAL_IDENTITY_ENVIRONMENT

---

CHANGELOG.md
lib/govuk_personalisation/version.rb

- Use GOVUK_ENVIRONMENT as a backstop for DIGITAL_IDENTITY_ENVIRONMENT ([#53](https://github.com/alphagov/govuk_personalisation/pull/53))
- Drop Ruby 2.7 support ([#51](https://github.com/alphagov/govuk_personalisation/pull/51))
https://trello.com/c/SiAQ3dZU/2086-redirect-govuk-account-to-homeaccountgovuk

Release version 0.14.0

---

CHANGELOG.md
lib/govuk_personalisation/urls.rb
spec/govuk_personalisation/urls_spec.rb

Updates the URLs for One Login URLs to match those available in One Login Home
Also:
- renames the methods to be more descriptive of actual use.
- adds aliases to the old names for the methods to ease transition (these can be removed when no longer needed)

Update URLs and method names for One Login

---

CHANGELOG.md
lib/govuk_personalisation/version.rb

- Update URLs and method names for One Login ([#56](https://github.com/alphagov/govuk_personalisation/pull/56))
- Note that this release deprecates the `your_account`, `manage`, `security`, and `feedback` methods of `GovukPersonalisation::Urls`, but retains them as aliases to allow easier transition. They will be removed in a later release.

Release version 0.15.0

---

lib/govuk_personalisation/urls.rb
spec/govuk_personalisation/urls_spec.rb

Their staging points to our integration and vice versa, so unless we do this mapping non-prod environments will end up with confusing user journeys.
https://gds.slack.com/archives/C012GEZBZM0/p1705490220168099

Map our environments correctly to DI/One Login's environments.

---

CHANGELOG.md
lib/govuk_personalisation/version.rb

- Update minimum required Ruby version ([#67](https://github.com/alphagov/govuk_personalisation/pull/67))
- Map our environments correctly to DI/One Login's environments. ([#63](https://github.com/alphagov/govuk_personalisation/pull/63))

Release version 0.16.0

---

CHANGELOG.md
lib/govuk_personalisation/version.rb

Release 1 
There are no substantive changes since 0.16.0 (only for dependabot merges and code tidying), so this is not breaking in practise. The gem has been in use for long enough that we should not keep marking it as a 0.x version.

Release 1.0.0

---

CHANGELOG.md
lib/govuk_personalisation/version.rb

- Update Rails requirements to allow Rails 8 ([#85](https://github.com/alphagov/govuk_personalisation/pull/85))

Release 1.1.0
